version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      # Restore cached dependencies
      - restore_cache:
          keys:
            - gradle-deps-v1-{{ checksum "build.gradle" }}
            - gradle-deps-v1-

      # Download and cache dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      # Cache the dependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-deps-v1-{{ checksum "build.gradle" }}

      # Run the build
      - run:
          name: Build
          command: ./gradlew build -x test

      # Run tests
      - run:
          name: Run Tests
          command: ./gradlew test

      # Store test results
      - store_test_results:
          path: build/test-results/test

      # Store test reports as artifacts
      - store_artifacts:
          path: build/reports/tests/test
          destination: test-reports

      # Store the built JAR as an artifact
      - store_artifacts:
          path: build/libs
          destination: libs

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
